[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
donate_crypto = "3B2UE8MjXCE2v5Ya5SJQBnRdyusN5Q4GRnKo9iYezjj4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
